# Sets Travis to run the Ruby specs on OS X machines to be as close as possible
# to the user environment.
#
language: objective-c

addons:
  code_climate:
    repo_token: ac16a75350b3a1f800cda5b913dabe4157fe5fce82bde75c62c9c5fb4dd8df27

env:
  - RVM_RUBY_VERSION=system

before_install:
  - export LANG=en_US.UTF-8
  - curl http://curl.haxx.se/ca/cacert.pem -o /usr/local/share/cacert.pem
  - source ~/.rvm/scripts/rvm
  - if [[ $RVM_RUBY_VERSION != 'system' ]]; then rvm install $RVM_RUBY_VERSION; fi
  - rvm use $RVM_RUBY_VERSION
  - if [[ $RVM_RUBY_VERSION == 'system' ]]; then sudo gem install bundler --no-ri --no-rdoc; else gem install bundler --no-ri --no-rdoc; fi


install:
  - sudo bundle install --without=documentation

script:
  - bundle exec pod setup --silent
  - bundle exec rake specs
